### ISSUE TITLE
Failed to activate the mei-friend package

### ISSUE THREAD

**Issue by wergo** [wergo/mei-friend#1]
Current version of mei-friend just loads verovio and displays version number.

1. Toggled package in Atom 1.53 (Mac OS Mojave).
2. Loading of current version of verovio 3.0.2 fails.

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.14.6
**Thrown From**: [mei-friend](https://github.com/wergo/mei-friend) package 0.1.1

### Stack Trace

Failed to activate the mei-friend package

```
At Cannot read property 'y' of undefined

TypeError: Cannot read property 'y' of undefined
    at /packages/mei-friend/node_modules/verovio/index.js:3:6238783)
    at /packages/mei-friend/node_modules/verovio/index.js:94:35)
    at Object.<anonymous> (/Users/werner/github/mei-friend/lib/mei-friend.js:13:15)
    at Object.<anonymous> (/Users/werner/github/mei-friend/lib/mei-friend.js:56:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:696929)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3581148)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3569132)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1879
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191492)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349897)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1230852)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1226986)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284919)
```

### Commands

```
     -0:02.5.0 mei-friend:toggle (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-xsltransform 1.0.0 
autocomplete-xml 0.11.0 
busy-signal 2.0.1 
intentions 1.1.5 
language-mei 0.34.5 
linter 3.2.3 
linter-autocomplete-jing 0.8.4 
linter-ui-default 2.4.0 
mei-friend 0.1.1 
xml-formatter 0.13.0 
```

**Comment by wergo** [comment]
... and the console throughs these errors alongside:
<img width="665" alt="grafik" src="https://user-images.githubusercontent.com/45632600/104157685-eb989f00-53eb-11eb-8b4c-f33040c3f819.png">

**Comment by lpugin** [comment]
When using NPM (latest versions) you need to wait for the package to load. See https://www.npmjs.com/package/verovio. You should add this somewhere
```
/* Wait for verovio to load */
verovio.module.onRuntimeInitialized = function ()
{
    /* create the toolkit instance */
    var vrvToolkit = new verovio.toolkit();
}
```

**Comment by wergo** [comment]
Thanks, @lpugin for pointing me to this. It works now.
